module.exports = {
  user: require('./usercontroller'),
  account: require('./accountcontroller'),
  provider: require('./providercontroller'),
  sales: require('./salescontroller'),
  agency: require('./agencycontroller'),
  order: require('./ordercontroller'),
  budget: require('./budgetcontroller'),
  activity: require('./activitycontroller'),
  campaign: require('./campaigncontroller'),
  engagement: require('./engagementcontroller'),
  status: require('./statuscontroller'),
  weeklyupdate: require('./weeklyupdatecontroller'),
  implementation: require('./implementationcontroller'),
  io: require('./insertionordercontroller'),
};
